### ISSUE TITLE
ToDo:

### ISSUE THREAD

**Issue by rc-117** [rc-117/HomeApp#7]
- [x] - Add 'Street Address' to Household (1/10 update - Created a class for street address)

- [ ] > - Incorporate into all Household creates, houseold GETs etc

- [ ] - create 'CreateHousholdJObject' and 'CreateHouseholdGroupJObject' and use in create actions

**Comment by rc-117** [comment]
Added the following to 'Household':

        public Address Address { get; set; }
        public Guid CreatorId { get; set; }
        public User Creator { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public AllowedUsers AllowedUsers { get; set; }

And the same to 'Household group'. 

- [ ] Need to edit the create methods for household and household groups to include above now."

**Comment by rc-117** [comment]
Added 'PhoneNumber' to User class.

- [ ] Need to edit 'CreateUser' methods to include PhoneNumber.

**Comment by rc-117** [comment]
AllowedUsers is for permission
- [ ] need to create an 'OwningUsers' for items that have scope over the household or a group like household rent or internet bills etc

**Comment by rc-117** [comment]
![image](https://user-images.githubusercontent.com/95998354/149267004-c93fae98-89cb-4009-adf4-afbd57c71e73.png)

Ensure that if a users are added to a household or household group, **they will have at minimum read access to the household or household group**

**Comment by rc-117** [comment]
![image](https://user-images.githubusercontent.com/95998354/149270034-b15c59c4-91aa-4d84-a2b9-6c0aaa9e74e9.png)
I split the data manager methods into smaller methods saving one type at a time, instead of user and household in one method. 
TODO: Create validation for household and household group

- [ ]

**Comment by rc-117** [comment]
![image](https://user-images.githubusercontent.com/95998354/149407272-213ece15-5530-42bb-b482-392a58650fba.png)

- [ ] Create output JSON for all the objects created in this action

**Comment by rc-117** [comment]
Cannot add or update a child row: a foreign key constraint fails (`test_db`.`households`, CONSTRAINT `FK_Households_Users_CreatorId` FOREIGN KEY (`CreatorId`) REFERENCES `users` (`Id`) ON DELETE RESTRICT)


This error is because the household is being saved before a user is even created

So the creator id is null

Need to save the user first without any houseold
